apiVersion: v1
kind: ServiceAccount
metadata:
  name: resilience-app
  namespace: resilience-app
  annotations:
    azure.workload.identity/client-id: "820556e4-8e39-4557-b275-d738badeea53"
  labels:
    azure.workload.identity/use: "true"
