apiVersion: v1
kind: Service
metadata:
  name: resilience-app
  namespace: resilience-app
  labels:
    app: resilience-app
spec:
  type: LoadBalancer

  selector:
    app: resilience-app

  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
