apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: resilience-app

resources:
  - ../../base

images:
  - name: resilience-app
    newName: coreresprodcusacr.azurecr.io/resilience-app
    newTag: "3"

patches:
  - path: configmap-patch.yaml
  - path: serviceaccount-patch.yaml
  - path: secretproviderclass-patch.yaml
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml
