apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: resilience-app-kv
  namespace: resilience-app
spec:
  parameters:
    clientID: "3994cb98-0f45-4876-860b-c8e347241ef3"
    keyvaultName: "core-res-prod-sin-kv"
